name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:edge
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update packages
        run: |
          mkdir artifacts
          echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
          apk update
          apk upgrade --no-cache
          apk add --no-cache python3 python3-dev py3-pip curl git github-cli binutils zstd usbmuxd@testing gcc python3-dev musl-dev linux-headers
      - name: Build JitStreamer
        run: |
          python3 -m venv jitstreamer_env
          . jitstreamer_env/bin/activate
          pip3 install git+https://github.com/jawshoeadan/JitStreamer#egg=JitStreamer
          tar cf - jitstreamer_env | zstd -T0 -19 > jitstreamer_env.tar.zst
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/voizun/jit_build.git
          cd jit_build
          gh release create "build-$(date +'%Y%m%d%H%M%S')" ../jitstreamer_env.tar.zst \
            --title "Jit and Tail bin"
