name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:edge
    permissions:
      contents: write
    steps:
      - name: Update packages
        run: |
          mkdir artifacts
          echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
          apk update
          apk upgrade --no-cache
          apk add --no-cache python3 python3-dev py3-pip gcc g++ curl git github-cli go binutils musl-dev linux-headers patchelf usbmuxd@testing
      - name: Install pip packages
        run: |
          pip3 install -U --break-system-packages pip nuitka git+https://github.com/jawshoeadan/JitStreamer#egg=JitStreamer
      - name: Clone JitStreamer
        run: git clone https://github.com/jawshoeadan/JitStreamer.git
      - name: Build with Nuitka
        run: |
          cd JitStreamer
          python3 -m nuitka --standalone --onefile --follow-imports JitStreamer/launch.py
      - run: ls -alh JitStreamer/build/
      - name: Build Tailscale
        run: |
          git clone https://github.com/tailscale/tailscale
          cd tailscale
          git checkout $(git describe --tags "$(git rev-list --tags --max-count=1)")
          go build -o tailscale.combined -tags ts_include_cli -ldflags="-s -w" -trimpath ./cmd/tailscaled
          strip tailscale.combined
          mv tailscale.combined ../artifacts/
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd artifacts
          tar cf - tailscale.combined *.bin | zstd -T0 -19 > bin.tar.zst
          gh release create "build-$(date +'%Y%m%d%H%M%S')" bin.tar.zst \
            --title "Jit and Tail bin"
